name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.anupams20 }}
        password: ${{ secrets.Sanupam2000@ }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: |
          your-dockerhub-anupams20/my_random_latest:latest
          your-dockerhub-anupams20/my_random_latest:${{ github.run_number }}
        cache-from: type=cache,mode=max
        cache-to: type=cache,mode=max
